# Generated by Django 3.2.18 on 2023-05-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='position',
            fields=[ ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),

            ],
        ),
    ]
