# Generated by Django 3.2.18 on 2023-05-11 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo1app', '0002_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='desc',
            new_name='descr',
        ),
    ]
